import type { InterviewRecord } from "./types";

export const SEED_INTERVIEWS: InterviewRecord[] = [
  {
    id: "demo_maya",
    demo: true,
    roleSlug: "server",
    status: "completed",
    pipelineStatus: "floor_invite",
    createdAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    durationSec: 11 * 60 + 20,
    sentToManager: true,
    candidate: {
      firstName: "Maya",
      lastName: "Chen",
      email: "maya.chen@email.com",
      phone: "(864) 555-0142",
      yearsExperience: "3–5 years",
      availability: ["Nights", "Weekends", "Lunch"],
      nightsWeekends: true,
      consent: true,
    },
    transcript: [
      {
        id: "t1",
        role: "assistant",
        text: "Hey Maya, I'm Cam, GM here at Chili's. Thanks for jumping in — this is a short server interview.",
        at: 0,
      },
      {
        id: "t2",
        role: "user",
        text: "Hey Cam. I've been serving at a busy Tex-Mex spot for four years, mostly nights. I like a full section.",
        at: 1,
      },
      {
        id: "t3",
        role: "assistant",
        text: "Love that. Walk me through a birthday table that gets a wrong steak while two other tables need you.",
        at: 2,
      },
      {
        id: "t4",
        role: "user",
        text: "I own it immediately, don't argue temps, get a manager if we need to comp dessert, fire a new steak, and I don't abandon the other tables — I set a time and come back.",
        at: 3,
      },
    ],
    floorAnswers: [
      {
        id: "f1",
        prompt: "Birthday table",
        choice: "Own it, get a manager if needed, fire a new steak, keep the other tables moving",
        correct: true,
        at: 1,
      },
      {
        id: "f2",
        prompt: "Allergy on the fly",
        choice: "Tell the kitchen immediately and stop the plate",
        correct: true,
        at: 2,
      },
    ],
    scorecard: {
      overallScore: 8.4,
      recommendation: "strong_yes",
      summary:
        "Maya sounds floor-ready. Clear guest recovery, nights/weekends are real, and she talks like someone who has run a full section. Bring her in this week.",
      strengths: [
        "Owns mistakes without getting defensive",
        "Protects other tables during a recovery",
        "Energy matches Chili's — warm, not stiff",
      ],
      developmentAreas: ["Menu upselling language can get more specific"],
      scores: {
        hospitality: 9,
        reliability: 8,
        teamwork: 8,
        guestRecovery: 9,
        foodKnowledge: 7,
        energy: 9,
        coachability: 8,
        rushJudgment: 9,
      },
      scenarioNotes: "Birthday steak recovery was specific and sequenced. Floor pop-ups both sound.",
      nextStep: "Invite to a 20-minute floor shadow this week. Cam should meet her in person.",
    },
  },
  {
    id: "demo_jordan",
    demo: true,
    roleSlug: "line-cook",
    status: "completed",
    pipelineStatus: "reviewing",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 175).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 162).toISOString(),
    durationSec: 9 * 60 + 40,
    sentToManager: true,
    candidate: {
      firstName: "Jordan",
      lastName: "Hale",
      email: "j.hale@email.com",
      phone: "(864) 555-0190",
      yearsExperience: "1–2 years",
      availability: ["Nights", "Weekends"],
      nightsWeekends: true,
      consent: true,
    },
    transcript: [
      {
        id: "t1",
        role: "assistant",
        text: "Jordan, I'm Cam. Line cook seat — tickets, timing, fajitas that still sizzle.",
        at: 0,
      },
      {
        id: "t2",
        role: "user",
        text: "I worked grill at a sports bar. I can hit temps. I get quiet when the board fills up but I don't walk.",
        at: 1,
      },
    ],
    floorAnswers: [
      {
        id: "f1",
        prompt: "Fajitas dying",
        choice: "Refire if they sat too long, communicate time, keep the rest of the board moving",
        correct: true,
        at: 1,
      },
    ],
    scorecard: {
      overallScore: 7.2,
      recommendation: "yes",
      summary:
        "Solid grill signal. Honest about going quiet in the weeds, which is coachable. Food safety answers were correct. Worth a trail shift.",
      strengths: ["Temps and ticket discipline", "Doesn't leave the line", "Allergy protocol was right"],
      developmentAreas: ["Needs to call Expo earlier when the board stacks"],
      scores: {
        hospitality: 6,
        reliability: 8,
        teamwork: 7,
        guestRecovery: 6,
        foodKnowledge: 8,
        energy: 7,
        coachability: 8,
        rushJudgment: 7,
      },
      scenarioNotes: "Refire instinct is there. Communication with Expo needs a nudge.",
      nextStep: "Trail on a Thursday dinner. Pair with a strong Expo.",
    },
  },
  {
    id: "demo_sam",
    demo: true,
    roleSlug: "host",
    status: "completed",
    pipelineStatus: "reviewing",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 8 + 120000).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 8 + 480000).toISOString(),
    durationSec: 6 * 60,
    sentToManager: true,
    candidate: {
      firstName: "Sam",
      lastName: "Ortiz",
      email: "sam.ortiz@email.com",
      phone: "(864) 555-0118",
      yearsExperience: "Under 1 year",
      availability: ["Lunch"],
      nightsWeekends: false,
      consent: true,
    },
    transcript: [
      {
        id: "t1",
        role: "assistant",
        text: "Sam, I'm Cam. Host is the first smile and the wait quote. How do you handle a 45-minute wait?",
        at: 0,
      },
      {
        id: "t2",
        role: "user",
        text: "I'd probably tell them it might be a little shorter so they don't leave. I can't do weekends because of school.",
        at: 1,
      },
    ],
    floorAnswers: [
      {
        id: "f1",
        prompt: "45-minute wait",
        choice: "Tell them 15 minutes so they don't leave",
        correct: false,
        at: 1,
      },
    ],
    scorecard: {
      overallScore: 5.4,
      recommendation: "maybe",
      summary:
        "Warm personality, but wait-quote honesty is a miss and weekends are off the table. Lunch-only host could work if you are desperate — otherwise hold.",
      strengths: ["Friendly presence", "Willing to learn"],
      developmentAreas: [
        "Do not underquote waits",
        "Weekend availability is a gap for this store",
      ],
      scores: {
        hospitality: 7,
        reliability: 4,
        teamwork: 6,
        guestRecovery: 5,
        foodKnowledge: 4,
        energy: 7,
        coachability: 6,
        rushJudgment: 4,
      },
      scenarioNotes: "Chose to underquote the wait. That's a trust problem at the door.",
      nextStep: "GM listen. Only bring in for lunch host if you can cover nights another way.",
    },
  },
  {
    id: "demo_riley",
    demo: true,
    roleSlug: "bartender",
    status: "completed",
    pipelineStatus: "passed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 26 + 60000).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 26 + 280000).toISOString(),
    durationSec: 4 * 60 + 10,
    sentToManager: true,
    candidate: {
      firstName: "Riley",
      lastName: "Brooks",
      email: "riley.b@email.com",
      phone: "(864) 555-0177",
      yearsExperience: "Under 1 year",
      availability: ["Nights"],
      nightsWeekends: true,
      consent: true,
    },
    transcript: [
      {
        id: "t1",
        role: "assistant",
        text: "Riley — bartender seat. Guest at the rail is drunk and asking for another margarita. Go.",
        at: 0,
      },
      {
        id: "t2",
        role: "user",
        text: "I'd probably still pour it if they're with friends. I don't want them to Yelp us.",
        at: 1,
      },
    ],
    floorAnswers: [
      {
        id: "f1",
        prompt: "One more round",
        choice: "Serve it — they're with a group that will handle it",
        correct: false,
        at: 1,
      },
    ],
    scorecard: {
      overallScore: 3.8,
      recommendation: "no",
      summary:
        "Responsible service miss is a hard no for the bar. Short interview, thin experience, and they would pour a drunk guest to avoid a review.",
      strengths: ["Showed up and answered"],
      developmentAreas: [
        "Cannot serve an intoxicated guest",
        "Needs TIPS-level judgment before a bar seat",
      ],
      scores: {
        hospitality: 5,
        reliability: 5,
        teamwork: 4,
        guestRecovery: 3,
        foodKnowledge: 3,
        energy: 5,
        coachability: 4,
        rushJudgment: 2,
      },
      scenarioNotes: "Would serve an intoxicated guest. Do not put them behind the bar.",
      nextStep: "Pass. If they want FOH, they would need a different seat and a different answer.",
    },
  },
];
