/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as DoneIdRouteImport } from './routes/done.$id'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as ManagerIdRouteImport } from './routes/manager_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneIdRoute = DoneIdRouteImport.update({
  id: '/done/$id',
  path: '/done/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIdRoute = ManagerIdRouteImport.update({
  id: '/manager_/$id',
  path: '/manager/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/done/$id': typeof DoneIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/manager/$id': typeof ManagerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/done/$id': typeof DoneIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/manager/$id': typeof ManagerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/done/$id': typeof DoneIdRoute
  '/interview/$id': typeof InterviewIdRoute
  '/manager_/$id': typeof ManagerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/apply'
    | '/login'
    | '/manager'
    | '/done/$id'
    | '/interview/$id'
    | '/manager/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/apply'
    | '/login'
    | '/manager'
    | '/done/$id'
    | '/interview/$id'
    | '/manager/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/apply'
    | '/login'
    | '/manager'
    | '/done/$id'
    | '/interview/$id'
    | '/manager_/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ApplyRoute: typeof ApplyRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  DoneIdRoute: typeof DoneIdRoute
  InterviewIdRoute: typeof InterviewIdRoute
  ManagerIdRoute: typeof ManagerIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done/$id': {
      id: '/done/$id'
      path: '/done/$id'
      fullPath: '/done/$id'
      preLoaderRoute: typeof DoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager_/$id': {
      id: '/manager_/$id'
      path: '/manager/$id'
      fullPath: '/manager/$id'
      preLoaderRoute: typeof ManagerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ApplyRoute: ApplyRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  DoneIdRoute: DoneIdRoute,
  InterviewIdRoute: InterviewIdRoute,
  ManagerIdRoute: ManagerIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
